In [1]:
import matplotlib.pyplot as plt
import pandas

import seaborn
seaborn.set_context('talk')
pandas.set_option("display.max_columns", None)

melb_df = pandas.read_csv('../data/non_nan_values_melb.csv')
melb_df[:3]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,suburb_count,CouncilArea_mode
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,137.374429,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,56,Yarra
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.000000,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,56,Yarra
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.000000,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,56,Yarra

In [2]:
melb_df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,suburb_count,CouncilArea_mode
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,137.374429,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,56,Yarra
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.000000,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,56,Yarra
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.000000,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,56,Yarra
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,137.374429,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,56,Yarra
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.000000,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,56,Yarra

## Exercise

- Using the reduced numerical features obtained with PCA in the practical
  exercise `01__practical_exercises.ipynb`.
- Then, apply MDS, LLE, Isomap, or TSNE.